name: flutter_geofencing
description: A new flutter plugin project.
version: 0.1.2
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.flutter.plugins.geofencing
    pluginClass: FlutterGeofencingPlugin
